/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-22 09:50:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.ctl.LoginCtl;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.ctl.BaseCtl;
import com.sunilos.p4.util.DataUtility;
import com.sunilos.p4.util.ServletUtility;
import com.sunilos.p4.util.MessageSource;

public final class LoginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/ors-tag-lib.tld", Long.valueOf(1780566788077L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.sunilos.p4.ctl.LoginCtl");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.BaseCtl");
    _jspx_imports_classes.add("com.sunilos.p4.util.DataUtility");
    _jspx_imports_classes.add("com.sunilos.p4.util.ServletUtility");
    _jspx_imports_classes.add("com.sunilos.p4.util.MessageSource");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fors_005fformMsg_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fors_005fformMsg_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fors_005fformMsg_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.sunilos.p4.bean.UserBean bean = null;
      bean = (com.sunilos.p4.bean.UserBean) _jspx_page_context.getAttribute("bean", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new com.sunilos.p4.bean.UserBean();
        _jspx_page_context.setAttribute("bean", bean, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

MessageSource ms = MessageSource.getInstance();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div\r\n");
      out.write("	class=\"container-fluid min-vh-100 d-flex align-items-center justify-content-center py-5\"\r\n");
      out.write("	style=\"background: linear-gradient(135deg, #e8f0fe 0%, #f1f5f9 100%);\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"col-12 col-sm-9 col-md-6 col-lg-4\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Card -->\r\n");
      out.write("		<div class=\"card border-0 shadow-lg rounded-4 overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Card header -->\r\n");
      out.write("			<div class=\"card-header text-white text-center py-4 border-0\"\r\n");
      out.write("				style=\"background: linear-gradient(135deg, #0d2137 0%, #1565c0 100%);\">\r\n");
      out.write("				<div class=\"d-flex justify-content-center mb-3\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("						style=\"width: 68px; height: 68px; background: rgba(255, 255, 255, 0.18); border: 2px solid rgba(255, 255, 255, 0.3); font-size: 1.9rem;\">\r\n");
      out.write("						<i class=\"fas fa-graduation-cap\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<h4 class=\"fw-bold mb-1\">\r\n");
      out.write("					");
      if (_jspx_meth_ors_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</h4>\r\n");
      out.write("				<p class=\"mb-0 opacity-75 small\">Online Result System</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Card body -->\r\n");
      out.write("			<div class=\"card-body px-4 py-4\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Form-level messages -->\r\n");
      out.write("				");
      if (_jspx_meth_ors_005fformMsg_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<form action=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Login ID -->\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label\r\n");
      out.write("							class=\"form-label fw-semibold text-secondary small text-uppercase tracking-wide\">\r\n");
      out.write("							<i class=\"bi bi-person-fill me-1\"></i>");
      out.print(ms.get("login.userid"));
      out.write("\r\n");
      out.write("							<span class=\"text-danger\">*</span>\r\n");
      out.write("						</label> <input type=\"text\" name=\"login\"\r\n");
      out.write("							class=\"form-control form-control-lg\"\r\n");
      out.write("							placeholder=\"Enter your login ID\"\r\n");
      out.write("							value=\"");
      out.print(DataUtility.getStringData(bean.getLogin()));
      out.write("\">\r\n");
      out.write("						");

						String loginErr = ServletUtility.getErrorMessage("login", request);
						if (loginErr != null && !loginErr.isEmpty()) {
						
      out.write("\r\n");
      out.write("						<div class=\"text-danger small mt-1\">\r\n");
      out.write("							<i class=\"bi bi-exclamation-circle\"></i>\r\n");
      out.write("							");
      out.print(loginErr);
      out.write("</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- Password -->\r\n");
      out.write("					<div class=\"mb-4\">\r\n");
      out.write("						<label\r\n");
      out.write("							class=\"form-label fw-semibold text-secondary small text-uppercase\">\r\n");
      out.write("							<i class=\"bi bi-lock-fill me-1\"></i>");
      out.print(ms.get("login.password"));
      out.write("\r\n");
      out.write("							<span class=\"text-danger\">*</span>\r\n");
      out.write("						</label> <input type=\"password\" name=\"password\"\r\n");
      out.write("							class=\"form-control form-control-lg\"\r\n");
      out.write("							placeholder=\"Enter your password\"\r\n");
      out.write("							value=\"");
      out.print(DataUtility.getStringData(bean.getPassword()));
      out.write("\">\r\n");
      out.write("						");

						String passErr = ServletUtility.getErrorMessage("password", request);
						if (passErr != null && !passErr.isEmpty()) {
						
      out.write("\r\n");
      out.write("						<div class=\"text-danger small mt-1\">\r\n");
      out.write("							<i class=\"bi bi-exclamation-circle\"></i>\r\n");
      out.write("							");
      out.print(passErr);
      out.write("</div>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- Submit -->\r\n");
      out.write("					<button type=\"submit\" name=\"operation\"\r\n");
      out.write("						class=\"btn btn-primary btn-lg w-100 fw-semibold\"\r\n");
      out.write("						style=\"background: linear-gradient(135deg, #1565c0, #0d47a1); border: none;\">\r\n");
      out.write("						<i class=\"bi bi-box-arrow-in-right me-2\"></i>\r\n");
      out.write("						");
      if (_jspx_meth_ors_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</button>\r\n");
      out.write("\r\n");
      out.write("					<!-- Footer links -->\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"d-flex justify-content-between align-items-center mt-4 pt-3 border-top\">\r\n");
      out.write("						<a href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\"\r\n");
      out.write("							class=\"text-success fw-semibold text-decoration-none small\">\r\n");
      out.write("							<i class=\"bi bi-person-plus-fill me-1\"></i>\r\n");
      out.write("						");
      if (_jspx_meth_ors_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</a> <a href=\"");
      out.print(ORSView.FORGET_PASSWORD_CTL);
      out.write("\"\r\n");
      out.write("							class=\"text-secondary text-decoration-none small\"> <i\r\n");
      out.write("							class=\"bi bi-question-circle me-1\"></i>\r\n");
      out.write("						");
      if (_jspx_meth_ors_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Below card -->\r\n");
      out.write("		<p class=\"text-center text-muted small mt-3\">&copy; 2024 Rays\r\n");
      out.write("			Technologies &mdash; Online Result System</p>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_ors_005fmessage_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f0 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f0.setParent(null);
      // /jsp/LoginView.jsp(36,5) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f0.setKey("login.title");
      int _jspx_eval_ors_005fmessage_005f0 = _jspx_th_ors_005fmessage_005f0.doStartTag();
      if (_jspx_th_ors_005fmessage_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fformMsg_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:formMsg
    com.sunilos.p4.tag.FormMessageTag _jspx_th_ors_005fformMsg_005f0 = (com.sunilos.p4.tag.FormMessageTag) _005fjspx_005ftagPool_005fors_005fformMsg_005fnobody.get(com.sunilos.p4.tag.FormMessageTag.class);
    try {
      _jspx_th_ors_005fformMsg_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fformMsg_005f0.setParent(null);
      int _jspx_eval_ors_005fformMsg_005f0 = _jspx_th_ors_005fformMsg_005f0.doStartTag();
      if (_jspx_th_ors_005fformMsg_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fformMsg_005fnobody.reuse(_jspx_th_ors_005fformMsg_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f1 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f1.setParent(null);
      // /jsp/LoginView.jsp(98,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f1.setKey("login.signin");
      int _jspx_eval_ors_005fmessage_005f1 = _jspx_th_ors_005fmessage_005f1.doStartTag();
      if (_jspx_th_ors_005fmessage_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f2 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f2.setParent(null);
      // /jsp/LoginView.jsp(107,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f2.setKey("login.signup");
      int _jspx_eval_ors_005fmessage_005f2 = _jspx_th_ors_005fmessage_005f2.doStartTag();
      if (_jspx_th_ors_005fmessage_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_ors_005fmessage_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  ors:message
    com.sunilos.p4.tag.MessageTag _jspx_th_ors_005fmessage_005f3 = (com.sunilos.p4.tag.MessageTag) _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.get(com.sunilos.p4.tag.MessageTag.class);
    try {
      _jspx_th_ors_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_ors_005fmessage_005f3.setParent(null);
      // /jsp/LoginView.jsp(111,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ors_005fmessage_005f3.setKey("login.forgotpassword");
      int _jspx_eval_ors_005fmessage_005f3 = _jspx_th_ors_005fmessage_005f3.doStartTag();
      if (_jspx_th_ors_005fmessage_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fors_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_ors_005fmessage_005f3);
    }
    return false;
  }
}
