/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-22 10:21:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.ctl.MyProfileCtl;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.util.HTMLUtility;
import java.util.HashMap;
import com.sunilos.p4.util.DataUtility;
import com.sunilos.p4.util.ServletUtility;

public final class MyProfileView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.sunilos.p4.ctl.MyProfileCtl");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.util.HTMLUtility");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.sunilos.p4.util.DataUtility");
    _jspx_imports_classes.add("com.sunilos.p4.util.ServletUtility");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.sunilos.p4.bean.UserBean bean = null;
      bean = (com.sunilos.p4.bean.UserBean) _jspx_page_context.getAttribute("bean", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new com.sunilos.p4.bean.UserBean();
        _jspx_page_context.setAttribute("bean", bean, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

    String _suc = ServletUtility.getSuccessMessage(request);
    String _err = ServletUtility.getErrorMessage(request);
    HashMap genderMap = new HashMap();
    genderMap.put("M", "Male");
    genderMap.put("F", "Female");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-4\" style=\"max-width:660px;\">\r\n");
      out.write("  <div class=\"card border-0 shadow-sm rounded-4 overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card-header text-white border-0 py-3 px-4\"\r\n");
      out.write("         style=\"background:linear-gradient(135deg,#0d2137 0%,#1565c0 100%);\">\r\n");
      out.write("      <h5 class=\"mb-0 fw-bold\">\r\n");
      out.write("        <i class=\"bi bi-person-circle me-2\"></i> My Profile\r\n");
      out.write("      </h5>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card-body px-4 py-4\">\r\n");
      out.write("\r\n");
      out.write("      ");
 if(_suc != null && !_suc.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-success py-2\"><i class=\"bi bi-check-circle-fill me-2\"></i>");
      out.print(_suc);
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      ");
 if(_err != null && !_err.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"alert alert-danger py-2\"><i class=\"bi bi-exclamation-triangle-fill me-2\"></i>");
      out.print(_err);
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <form action=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\" method=\"POST\">\r\n");
      out.write("        <input type=\"hidden\" name=\"id\"              value=\"");
      out.print(bean.getId());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"createdBy\"        value=\"");
      out.print(bean.getCreatedBy());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"modifiedBy\"       value=\"");
      out.print(bean.getModifiedBy());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"createdDatetime\"  value=\"");
      out.print(DataUtility.getTimestamp(bean.getCreatedDatetime()));
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"modifiedDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(bean.getModifiedDatetime()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("          <label class=\"form-label fw-semibold\">Login ID</label>\r\n");
      out.write("          <input type=\"text\" name=\"login\" class=\"form-control bg-light\" readonly\r\n");
      out.write("                 value=\"");
      out.print(DataUtility.getStringData(bean.getLogin()));
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row g-3 mb-3\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <label class=\"form-label fw-semibold\">First Name <span class=\"text-danger\">*</span></label>\r\n");
      out.write("            <input type=\"text\" name=\"firstName\" class=\"form-control\"\r\n");
      out.write("                   value=\"");
      out.print(DataUtility.getStringData(bean.getFirstName()));
      out.write("\">\r\n");
      out.write("            <div class=\"text-danger small mt-1\">");
      out.print(ServletUtility.getErrorMessage("firstName", request));
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <label class=\"form-label fw-semibold\">Last Name <span class=\"text-danger\">*</span></label>\r\n");
      out.write("            <input type=\"text\" name=\"lastName\" class=\"form-control\"\r\n");
      out.write("                   value=\"");
      out.print(DataUtility.getStringData(bean.getLastName()));
      out.write("\">\r\n");
      out.write("            <div class=\"text-danger small mt-1\">");
      out.print(ServletUtility.getErrorMessage("lastName", request));
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row g-3 mb-3\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <label class=\"form-label fw-semibold\">Gender</label>\r\n");
      out.write("            ");
      out.print(HTMLUtility.getList("gender", bean.getGender(), genderMap));
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <label class=\"form-label fw-semibold\">Mobile No <span class=\"text-danger\">*</span></label>\r\n");
      out.write("            <input type=\"text\" name=\"mobileNo\" class=\"form-control\"\r\n");
      out.write("                   value=\"");
      out.print(DataUtility.getStringData(bean.getMobileNo()));
      out.write("\">\r\n");
      out.write("            <div class=\"text-danger small mt-1\">");
      out.print(ServletUtility.getErrorMessage("mobileNo", request));
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mb-4\">\r\n");
      out.write("          <label class=\"form-label fw-semibold\">Date of Birth (mm/dd/yyyy)</label>\r\n");
      out.write("          <div class=\"input-group\">\r\n");
      out.write("            <input type=\"text\" name=\"dob\" id=\"udate\" class=\"form-control\" readonly\r\n");
      out.write("                   value=\"");
      out.print(DataUtility.getDateString(bean.getDob()));
      out.write("\">\r\n");
      out.write("            <a class=\"btn btn-outline-secondary\">\r\n");
      out.write("              <img src=\"../img/cal.jpg\" width=\"16\" height=\"15\" alt=\"Calendar\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text-danger small mt-1\">");
      out.print(ServletUtility.getErrorMessage("dob", request));
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex gap-2 pt-2 border-top\">\r\n");
      out.write("          <button type=\"submit\" name=\"operation\" value=\"");
      out.print(MyProfileCtl.OP_SAVE);
      out.write("\" class=\"btn btn-primary\">\r\n");
      out.write("            <i class=\"bi bi-save me-1\"></i> Save\r\n");
      out.write("          </button>\r\n");
      out.write("          <button type=\"submit\" name=\"operation\" value=\"");
      out.print(MyProfileCtl.OP_CHANGE_MY_PASSWORD);
      out.write("\"\r\n");
      out.write("                  class=\"btn btn-outline-warning\">\r\n");
      out.write("            <i class=\"bi bi-key me-1\"></i> Change Password\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
