/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-22 09:50:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.bean.ProductBean;
import com.sunilos.p4.ctl.BaseCtl;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.util.ServletUtility;
import java.util.List;
import java.util.Iterator;
import com.sunilos.p4.ctl.BaseCtl;
import com.sunilos.p4.util.ServletUtility;
import java.util.List;

public final class ProductListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/ListFooter.jsp", Long.valueOf(1780566788093L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.sunilos.p4.bean.ProductBean");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.BaseCtl");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.util.ServletUtility");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int pageNo = ServletUtility.getPageNo(request);
int pageSize = ServletUtility.getPageSize(request);
int index = ((pageNo - 1) * pageSize) + 1;
List list = ServletUtility.getList(request);
Iterator<ProductBean> it = list.iterator();
String _err = ServletUtility.getErrorMessage(request);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid px-4 py-4\" style=\"max-width: 900px;\">\r\n");
      out.write("	<div class=\"card border-0 shadow-sm rounded-4 overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"card-header text-white border-0 py-3 px-4 d-flex justify-content-between align-items-center\"\r\n");
      out.write("			style=\"background: linear-gradient(135deg, #0d2137 0%, #1565c0 100%);\">\r\n");
      out.write("			<h5 class=\"mb-0 fw-bold\">\r\n");
      out.write("				<i class=\"bi bi-bookmark-star-fill me-2\"></i> Subject List\r\n");
      out.write("			</h5>\r\n");
      out.write("			<div class=\"d-flex gap-2\">\r\n");
      out.write("				<a href=\"");
      out.print(ORSView.PRODUCT_REPORT_CTL);
      out.write("\" target=\"_blank\"\r\n");
      out.write("					class=\"btn btn-sm btn-warning fw-semibold\"> <i\r\n");
      out.write("					class=\"bi bi-file-earmark-pdf me-1\"></i> Print PDF\r\n");
      out.write("				</a> <a href=\"");
      out.print(ORSView.PRODUCT_REPORT_CTL);
      out.write("?type=doc\" target=\"_blank\"\r\n");
      out.write("					class=\"btn btn-sm btn-info fw-semibold\"> <i\r\n");
      out.write("					class=\"bi bi-file-earmark-word me-1\"></i> Print DOC\r\n");
      out.write("				</a> <a href=\"");
      out.print(ORSView.PRODUCT_CTL);
      out.write("\"\r\n");
      out.write("					class=\"btn btn-sm btn-light text-primary fw-semibold\"> <i\r\n");
      out.write("					class=\"bi bi-plus-circle me-1\"></i> Add Product\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"");
      out.print(ORSView.PRODUCT_LIST_CTL);
      out.write("\" method=\"POST\">\r\n");
      out.write("			<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\"> <input\r\n");
      out.write("				type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"p-3 bg-light border-bottom d-flex flex-wrap gap-2 align-items-center\">\r\n");
      out.write("				<input type=\"text\" name=\"name\" class=\"form-control form-control-sm\"\r\n");
      out.write("					style=\"max-width: 220px;\" placeholder=\"Search by ProductName\"\r\n");
      out.write("					value=\"");
      out.print(ServletUtility.getParameter("name", request));
      out.write("\">\r\n");
      out.write("				<button type=\"submit\" name=\"operation\"\r\n");
      out.write("					value=\"");
      out.print(BaseCtl.OP_SEARCH);
      out.write("\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("					<i class=\"bi bi-search me-1\"></i> Search\r\n");
      out.write("				</button>\r\n");
      out.write("				<button type=\"submit\" name=\"operation\"\r\n");
      out.write("					value=\"");
      out.print(BaseCtl.OP_DELETE);
      out.write("\"\r\n");
      out.write("					class=\"btn btn-danger btn-sm ms-auto\"\r\n");
      out.write("					onclick=\"return confirm('Delete selected subjects?')\">\r\n");
      out.write("					<i class=\"bi bi-trash me-1\"></i> Delete Selected\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			if (_err != null && !_err.isEmpty()) {
			
      out.write("\r\n");
      out.write("			<div class=\"alert alert-danger py-2 mx-3 mt-3\">\r\n");
      out.write("				<i class=\"bi bi-exclamation-triangle-fill me-2\"></i>");
      out.print(_err);
      out.write("</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"table-responsive\">\r\n");
      out.write("				<table class=\"table table-hover align-middle mb-0\">\r\n");
      out.write("					<thead class=\"table-light\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th width=\"40\"><input type=\"checkbox\"\r\n");
      out.write("								onclick=\"document.querySelectorAll('input[name=ids]').forEach(c=>c.checked=this.checked)\"></th>\r\n");
      out.write("							<th>S.No</th>\r\n");
      out.write("\r\n");
      out.write("							<th>Product Name</th>\r\n");
      out.write("							<th>Category</th>\r\n");
      out.write("							<th>Order Date</th>\r\n");
      out.write("							<th>Price</th>\r\n");
      out.write("\r\n");
      out.write("							<th>Action</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						while (it.hasNext()) {
							ProductBean bean = it.next();
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><input type=\"checkbox\" name=\"ids\"\r\n");
      out.write("								value=\"");
      out.print(bean.getId());
      out.write("\"></td>\r\n");
      out.write("							<td class=\"text-muted small\">");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("							<td class=\"fw-semibold\">");
      out.print(bean.getProductName());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(bean.getProductCategory());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(bean.getOrderDate());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(bean.getPrice());
      out.write("</td>\r\n");
      out.write("							<td><a href=\"ProductCtl?id=");
      out.print(bean.getId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-sm btn-outline-primary\"> <i\r\n");
      out.write("									class=\"bi bi-pencil\"></i> Edit\r\n");
      out.write("							</a></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"p-3 border-top\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

int pageNo1 = ServletUtility.getPageNo(request);
List nextList = (List) request.getAttribute("nextList");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"d-flex justify-content-center align-items-center gap-2\">\r\n");
      out.write("	<button type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_PREVIOUS);
      out.write("\"\r\n");
      out.write("		class=\"btn btn-outline-primary btn-sm\"\r\n");
      out.write("		");
      out.print(pageNo1 == 1 ? "disabled" : "");
      out.write(">\r\n");
      out.write("		<i class=\"bi bi-chevron-left\"></i> Previous\r\n");
      out.write("	</button>\r\n");
      out.write("	<button type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_NEXT);
      out.write("\"\r\n");
      out.write("		class=\"btn btn-outline-primary btn-sm\"\r\n");
      out.write("		");
      out.print(nextList.size() == 0 ? "disabled" : "");
      out.write(">\r\n");
      out.write("		Next <i class=\"bi bi-chevron-right\"></i>\r\n");
      out.write("	</button>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
