/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-22 09:50:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.bean.UserBean;
import com.sunilos.p4.bean.RoleBean;

public final class Welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.bean.UserBean");
    _jspx_imports_classes.add("com.sunilos.p4.bean.RoleBean");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

UserBean currentUser = (UserBean) session.getAttribute("user");
boolean loggedIn = currentUser != null;
boolean isStudent = loggedIn && currentUser.getRoleId() == RoleBean.STUDENT;
boolean isAdmin = loggedIn && currentUser.getRoleId() == RoleBean.ADMIN;
String firstName = loggedIn ? currentUser.getFirstName() : "Guest";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid px-4 py-4\" style=\"max-width: 1100px;\">\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Hero Banner ===== -->\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"rounded-4 text-white p-4 p-md-5 mb-4 d-flex align-items-center gap-4 shadow\"\r\n");
      out.write("		style=\"background: linear-gradient(135deg, #0d2137 0%, #1565c0 100%);\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"flex-shrink-0 rounded-circle d-flex align-items-center justify-content-center\"\r\n");
      out.write("			style=\"width: 80px; height: 80px; background: rgba(255, 255, 255, 0.15); border: 2px solid rgba(255, 255, 255, 0.25); font-size: 2.3rem;\">\r\n");
      out.write("			<i class=\"fas fa-graduation-cap\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<h1 class=\"fw-bold mb-1 fs-2\">\r\n");
      out.write("				Welcome");

			if (loggedIn) {
			
      out.write(",\r\n");
      out.write("				");
      out.print(firstName);
      out.write('!');

			} else {
			
      out.write("\r\n");
      out.write("				to ORS");

			}
			
      out.write("\r\n");
      out.write("			</h1>\r\n");
      out.write("			<p class=\"mb-0 opacity-75\">Online Result System &mdash; Powered\r\n");
      out.write("				by Rays Technologies</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Section label ===== -->\r\n");
      out.write("	<p class=\"text-uppercase text-muted fw-semibold small mb-3\"\r\n");
      out.write("		style=\"letter-spacing: .08em;\">\r\n");
      out.write("		");

		if (isAdmin) {
		
      out.write("Administration Panel\r\n");
      out.write("		");

		} else if (isStudent) {
		
      out.write("Quick Access\r\n");
      out.write("		");

		} else {
		
      out.write("Get Started");

		}
		
      out.write("\r\n");
      out.write("	</p>\r\n");
      out.write("\r\n");
      out.write("	<!-- ===== Dashboard Cards ===== -->\r\n");
      out.write("	<div class=\"row g-3\">\r\n");
      out.write("\r\n");
      out.write("		");

		if (isStudent) {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-primary\">\r\n");
      out.write("					<div class=\"fs-1 text-primary mb-2\">\r\n");
      out.write("						<i class=\"bi bi-file-earmark-text-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">My Marksheet</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">View your academic results</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-success\">\r\n");
      out.write("					<div class=\"fs-1 text-success mb-2\">\r\n");
      out.write("						<i class=\"bi bi-person-circle\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">My Profile</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">View and edit your details</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"\r\n");
      out.write("				class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-warning\">\r\n");
      out.write("					<div class=\"fs-1 text-warning mb-2\">\r\n");
      out.write("						<i class=\"bi bi-key-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Change Password</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Update your login password</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"\r\n");
      out.write("				class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-danger\">\r\n");
      out.write("					<div class=\"fs-1 text-danger mb-2\">\r\n");
      out.write("						<i class=\"bi bi-trophy-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Merit List</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">View class rankings</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");

		} else if (isAdmin) {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-primary\">\r\n");
      out.write("					<div class=\"fs-1 text-primary mb-2\">\r\n");
      out.write("						<i class=\"bi bi-people-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Users</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Manage system users</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-success\">\r\n");
      out.write("					<div class=\"fs-1 text-success mb-2\">\r\n");
      out.write("						<i class=\"bi bi-bank2\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Colleges</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Manage college records</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card\"\r\n");
      out.write("					style=\"border-top: 4px solid #7c3aed;\">\r\n");
      out.write("					<div class=\"fs-1 mb-2\" style=\"color: #7c3aed;\">\r\n");
      out.write("						<i class=\"bi bi-mortarboard-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Students</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Manage student records</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"\r\n");
      out.write("				class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-warning\">\r\n");
      out.write("					<div class=\"fs-1 text-warning mb-2\">\r\n");
      out.write("						<i class=\"bi bi-file-earmark-text-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Marksheets</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Manage marksheet records</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-danger\">\r\n");
      out.write("					<div class=\"fs-1 text-danger mb-2\">\r\n");
      out.write("						<i class=\"bi bi-shield-fill-check\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Roles</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Manage user roles</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"\r\n");
      out.write("				class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card\"\r\n");
      out.write("					style=\"border-top: 4px solid #0d9488;\">\r\n");
      out.write("					<div class=\"fs-1 mb-2\" style=\"color: #0d9488;\">\r\n");
      out.write("						<i class=\"bi bi-trophy-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Merit List</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">View merit rankings</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-primary\">\r\n");
      out.write("					<div class=\"fs-1 text-primary mb-2\">\r\n");
      out.write("						<i class=\"bi bi-search\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Get Marksheet</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Lookup a marksheet</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card\"\r\n");
      out.write("					style=\"border-top: 4px solid #374151;\">\r\n");
      out.write("					<div class=\"fs-1 mb-2\" style=\"color: #374151;\">\r\n");
      out.write("						<i class=\"bi bi-person-gear\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">My Profile</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">View and edit your profile</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card\"\r\n");
      out.write("					style=\"border-top: 4px solid #0891b2;\">\r\n");
      out.write("					<div class=\"fs-1 mb-2\" style=\"color: #0891b2;\">\r\n");
      out.write("						<i class=\"bi bi-person-badge-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Faculty</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Manage faculty records</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-primary\">\r\n");
      out.write("					<div class=\"fs-1 text-primary mb-2\">\r\n");
      out.write("						<i class=\"bi bi-box-arrow-in-right\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Login</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Sign in to your account</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\"\r\n");
      out.write("				class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card border-top border-4 border-success\">\r\n");
      out.write("					<div class=\"fs-1 text-success mb-2\">\r\n");
      out.write("						<i class=\"bi bi-person-plus-fill\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Register</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Create a new account</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-6 col-md-4 col-lg-3\">\r\n");
      out.write("			<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\" class=\"text-decoration-none\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"card h-100 border-0 shadow-sm rounded-4 text-center p-3 ors-card\"\r\n");
      out.write("					style=\"border-top: 4px solid #7c3aed;\">\r\n");
      out.write("					<div class=\"fs-1 mb-2\" style=\"color: #7c3aed;\">\r\n");
      out.write("						<i class=\"bi bi-search\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 class=\"fw-bold mb-1\">Get Marksheet</h6>\r\n");
      out.write("					<p class=\"text-muted small mb-0\">Search for a marksheet</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /row -->\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
