/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-22 09:50:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.util.DataValidator;
import com.sunilos.p4.util.MessageSource;
import com.sunilos.p4.util.MessageSource;
import com.sunilos.p4.bean.RoleBean;
import com.sunilos.p4.ctl.LoginCtl;
import com.sunilos.p4.bean.UserBean;
import com.sunilos.p4.ctl.ORSView;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1782112486955L));
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1780566788093L));
    _jspx_dependants.put("/WEB-INF/ors-tag-lib.tld", Long.valueOf(1780566788077L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.util.DataValidator");
    _jspx_imports_classes.add("com.sunilos.p4.util.MessageSource");
    _jspx_imports_classes.add("com.sunilos.p4.bean.RoleBean");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.LoginCtl");
    _jspx_imports_classes.add("com.sunilos.p4.bean.UserBean");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<title>ORS - Online Result System</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(contextPath);
      out.write("/img/favicon.ico\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 5 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Application CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(contextPath);
      out.write("/css/app.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery UI -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath);
      out.write("/js/datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"d-flex flex-column min-vh-100\">\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

MessageSource ms = MessageSource.getInstance();
String locale = ms.getLanguage();
UserBean userBean = (UserBean) session.getAttribute("user");
boolean loggedIn = userBean != null;
boolean isAdmin = loggedIn && userBean.getRoleId() == RoleBean.ADMIN;
boolean isStudent = loggedIn && userBean.getRoleId() == RoleBean.STUDENT;
String displayName = loggedIn ? userBean.getFirstName() + " (" + session.getAttribute("role") + ")" : "Guest";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark py-0\"\r\n");
      out.write("	style=\"background: linear-gradient(135deg, #0d2137 0%, #1565c0 100%); min-height: 58px;\">\r\n");
      out.write("	<div class=\"container-fluid px-4\">\r\n");
      out.write("\r\n");
      out.write("		<!-- ===== Brand ===== -->\r\n");
      out.write("		<a class=\"navbar-brand fw-bold d-flex align-items-center gap-2 py-2\"\r\n");
      out.write("			href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"> <img\r\n");
      out.write("			src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/customLogo.jpg\" alt=\"ORS\"\r\n");
      out.write("			height=\"34\" class=\"rounded\" style=\"object-fit: contain;\"> <span>ORS</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<!-- Mobile toggler -->\r\n");
      out.write("		<button class=\"navbar-toggler border-0\" type=\"button\"\r\n");
      out.write("			data-bs-toggle=\"collapse\" data-bs-target=\"#mainNav\"\r\n");
      out.write("			aria-controls=\"mainNav\" aria-expanded=\"false\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"mainNav\">\r\n");
      out.write("\r\n");
      out.write("			<!-- ===== Left nav â grouped dropdowns (logged-in only) ===== -->\r\n");
      out.write("			");

			if (loggedIn) {
			
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav me-auto gap-0\">\r\n");
      out.write("\r\n");
      out.write("				<!-- ---- Marksheet ---- -->\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle px-3 py-3\" href=\"#\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("						class=\"bi bi-file-earmark-text me-1\"></i> Marksheet\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-dark shadow border-0 rounded-3\"\r\n");
      out.write("						style=\"min-width: 200px; background: #1a2e4a;\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-search me-1\"></i> Query\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-search me-2 text-info\"></i> Get Marksheet\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-trophy me-2 text-warning\"></i> Merit List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						");

						if (isAdmin) {
						
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider border-secondary\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-gear me-1\"></i> Manage\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-plus-circle me-2 text-success\"></i> Add Marksheet\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-list-ul me-2 text-primary\"></i> Marksheet List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- ---- Academics: Colleges / Courses / Subjects (Admin only) ---- -->\r\n");
      out.write("				");

				if (isAdmin) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle px-3 py-3\" href=\"#\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("						class=\"bi bi-mortarboard me-1\"></i> Academics\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-dark shadow border-0 rounded-3\"\r\n");
      out.write("						style=\"min-width: 210px; background: #1a2e4a;\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Colleges -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-bank2 me-1\"></i> Colleges\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-plus-circle me-2 text-success\"></i> Add College\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-building me-2 text-primary\"></i> College List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Courses -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-journal-bookmark me-1\"></i> Courses\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-plus-circle me-2 text-success\"></i> Add Course\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-list-ul me-2 text-primary\"></i> Course List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Subjects -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-card-text me-1\"></i> Subjects\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-plus-circle me-2 text-success\"></i> Add Subject\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-list-ul me-2 text-primary\"></i> Subject List\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- ---- People: Students / Faculty / Users / Roles (Admin only) ---- -->\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle px-3 py-3\" href=\"#\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("						class=\"bi bi-people me-1\"></i> People\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-dark shadow border-0 rounded-3\"\r\n");
      out.write("						style=\"min-width: 210px; background: #1a2e4a;\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Students -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-mortarboard me-1\"></i> Students\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-person-plus me-2 text-success\"></i> Add Student\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-people me-2 text-primary\"></i> Student List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Faculty -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-person-badge me-1\"></i> Faculty\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-plus-circle me-2 text-success\"></i> Add Faculty\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-person-lines-fill me-2 text-primary\"></i> Faculty\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Users -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-person-gear me-1\"></i> Users\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-person-plus me-2 text-success\"></i> Add User\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-person-lines-fill me-2 text-primary\"></i> User List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Roles -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-shield-check me-1\"></i> Roles\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-plus-circle me-2 text-success\"></i> Add Role\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-shield-fill-check me-2 text-primary\"></i> Role List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Product -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-info small\">\r\n");
      out.write("								<i class=\"bi bi-person-gear me-1\"></i> Product\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.PRODUCT_CTL);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-person-plus me-2 text-success\"></i> Add Product\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.PRODUCT_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-person-lines-fill me-2 text-primary\"></i> Product\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- ---- Reports (Admin only) ---- -->\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle px-3 py-3\" href=\"#\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("						class=\"bi bi-file-earmark-bar-graph me-1\"></i> Reports\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-dark shadow border-0 rounded-3\"\r\n");
      out.write("						style=\"min-width: 230px; background: #1a2e4a;\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Academics -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-warning small\">\r\n");
      out.write("								<i class=\"bi bi-mortarboard me-1\"></i> Academics\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.COLLEGE_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> College\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.COURSE_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> Course\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.SUBJECT_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> Subject\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- People -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-warning small\">\r\n");
      out.write("								<i class=\"bi bi-people me-1\"></i> People\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.STUDENT_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> Student\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.FACULTY_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> Faculty\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.USER_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> User List\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.ROLE_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> Role List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><hr class=\"dropdown-divider border-secondary\"></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Results -->\r\n");
      out.write("						<li>\r\n");
      out.write("							<h6 class=\"dropdown-header text-uppercase text-warning small\">\r\n");
      out.write("								<i class=\"bi bi-clipboard-data me-1\"></i> Results\r\n");
      out.write("							</h6>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_REPORT_CTL);
      out.write("\" target=\"_blank\"> <i\r\n");
      out.write("								class=\"bi bi-file-earmark-pdf me-2 text-warning\"></i> Marksheet\r\n");
      out.write("								List\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			<ul class=\"navbar-nav me-auto\"></ul>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- ===== Right side ===== -->\r\n");
      out.write("			<ul class=\"navbar-nav align-items-lg-center gap-1 ms-2\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Language -->\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<form class=\"d-flex align-items-center m-0\">\r\n");
      out.write("						<select class=\"form-select form-select-sm border-0 py-1\"\r\n");
      out.write("							name=\"lang\" id=\"lang\" onchange=\"this.form.submit()\"\r\n");
      out.write("							style=\"width: 120px; background: rgba(255, 255, 255, 0.12); color: #fff; font-size: 0.82rem; cursor: pointer;\">\r\n");
      out.write("							<option value=\"en\" ");
      out.print(("en".equals(locale)) ? "selected" : "");
      out.write("\r\n");
      out.write("								style=\"background: #0d2137; color: #fff;\">&#127758;\r\n");
      out.write("								English</option>\r\n");
      out.write("							<option value=\"hi\" ");
      out.print(("hi".equals(locale)) ? "selected" : "");
      out.write("\r\n");
      out.write("								style=\"background: #0d2137; color: #fff;\">&#127470;&#127475;\r\n");
      out.write("								Hindi</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</form>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<!-- Home -->\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link px-2\"\r\n");
      out.write("					href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"> <i class=\"bi bi-house-fill\"></i>\r\n");
      out.write("						<span class=\"d-lg-none ms-1\">Home</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<!-- My Account dropdown (logged-in) -->\r\n");
      out.write("				");

				if (loggedIn) {
				
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle d-flex align-items-center gap-1 px-2\"\r\n");
      out.write("					href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <span\r\n");
      out.write("						class=\"rounded-circle bg-white text-primary d-flex align-items-center justify-content-center fw-bold\"\r\n");
      out.write("						style=\"width: 28px; height: 28px; font-size: 0.75rem; flex-shrink: 0;\">\r\n");
      out.write("							");
      out.print(userBean.getFirstName().substring(0, 1).toUpperCase());
      out.write("\r\n");
      out.write("					</span> <span class=\"d-none d-lg-inline small\">");
      out.print(userBean.getFirstName());
      out.write("</span>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-dark dropdown-menu-end shadow border-0 rounded-3\"\r\n");
      out.write("						style=\"min-width: 210px; background: #1a2e4a;\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"px-3 py-2 border-bottom border-secondary\">\r\n");
      out.write("								<div class=\"text-white fw-semibold small\">\r\n");
      out.write("									");
      out.print(displayName);
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"text-white-50\" style=\"font-size: 0.75rem;\">\r\n");
      out.write("									");
      out.print(userBean.getLogin());
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item mt-1\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-person-circle me-2 text-info\"></i> My Profile\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-key me-2 text-warning\"></i> Change Password\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\"> <i\r\n");
      out.write("								class=\"bi bi-book me-2 text-success\"></i> Java Doc\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider border-secondary\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item text-danger\"\r\n");
      out.write("							href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">\r\n");
      out.write("								<i class=\"bi bi-box-arrow-right me-2\"></i> Logout\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<!-- Login button (guest) -->\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					class=\"btn btn-sm btn-outline-light ms-1 px-3\"\r\n");
      out.write("					href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"> <i\r\n");
      out.write("						class=\"bi bi-box-arrow-in-right me-1\"></i> Login\r\n");
      out.write("				</a></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String viewName = request.getParameter("p");

	if (DataValidator.isNull(viewName)) {
		viewName = (String) request.getAttribute("p");
	}

	if (DataValidator.isNull(viewName)) {
		viewName = "jsp/404.jsp";
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main class=\"flex-grow-1\">\r\n");
      out.write("		<div class=\"page-content\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, viewName, out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".footer {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background: linear-gradient(135deg, #0d2137 0%, #1565c0 100%);\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 12px 0;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	box-shadow: 0 -2px 8px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer small {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	letter-spacing: 0.3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer strong {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("		<small> <strong>&copy; 2025 Rays EdTech</strong> &nbsp;|&nbsp;\r\n");
      out.write("			Online Result System &nbsp;|&nbsp; All Rights Reserved\r\n");
      out.write("		</small>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JS -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
