/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.116
 * Generated at: 2026-06-01 08:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.proj4.controller.VehicleCtl;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.ServletUtility;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.bean.UserBean;

public final class VehicleView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1777976321979L));
    _jspx_dependants.put("/jsp/ModuleView.jsp", Long.valueOf(1780297146469L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("in.co.rays.proj4.controller.VehicleCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add Vehicle</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("	href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"");
      out.print(ORSView.VEHICLE_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Module Page</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/ORSProject-04/js/checkbox.js\"></script>\r\n");
      out.write("<script src=\"/ORSProject-04/js/datepicker.js\"></script>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\r\n");
      out.write("	href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Logo -->\r\n");
      out.write("	<img src=\"");
      out.print(request.getContextPath());
      out.write("/img/customLogo.jpg\"\r\n");
      out.write("		align=\"right\" width=\"100\" height=\"40\" border=\"0\">\r\n");
      out.write("	");

	UserBean user = (UserBean) session.getAttribute("user");
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	if (user != null) {
	
      out.write("\r\n");
      out.write("	<h3>\r\n");
      out.write("		Hi,\r\n");
      out.write("		");
      out.print(user.getFirstName());
      out.write("\r\n");
      out.write("		(");
      out.print(session.getAttribute("role"));
      out.write(")\r\n");
      out.write("	</h3>\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.MEETING_CTL);
      out.write("\">Add Meeting</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.MEETING_LIST_CTL);
      out.write("\">List Meeting</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.VEHICLE_CTL);
      out.write("\">Add Vehicle</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.VEHICLE_LIST_CTL);
      out.write("\">List Vehicle</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.LIBRARY_CTL);
      out.write("\">Add Library</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.LIBRARY_LIST_CTL);
      out.write("\">List Library</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.BUS_CTL);
      out.write("\">Add Bus</a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.BUS_LIST_CTL);
      out.write("\">Bus List </a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- <h1 align=\"center\">\r\n");
      out.write("		<font size=\"10px\" color=\"navy\">Daily Module page</font>\r\n");
      out.write("	</h1>\r\n");
      out.write("	 -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#footer {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<CENTER>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<H3>All rights reserved by Rays Technologies, SunilOS Infotech\r\n");
      out.write("				Pvt Ltd Copyright &copy; 2024</H3>\r\n");
      out.write("		</CENTER>\r\n");
      out.write("	</div>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");
      in.co.rays.proj4.bean.VehicleBean bean = null;
      bean = (in.co.rays.proj4.bean.VehicleBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.proj4.bean.VehicleBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\r\n");
        out.write("		");
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("			<h1 align=\"center\" style=\"margin-bottom: -15; color: navy\">\r\n");
      out.write("\r\n");
      out.write("				");

				if (bean != null && bean.getId() > 0) {
				
      out.write("\r\n");
      out.write("				Update\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				Add\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				Vehicle\r\n");
      out.write("\r\n");
      out.write("			</h1>\r\n");
      out.write("\r\n");
      out.write("			<div style=\"height: 15px; margin-bottom: 12px\">\r\n");
      out.write("\r\n");
      out.write("				<H3 align=\"center\">\r\n");
      out.write("\r\n");
      out.write("					<font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</font>\r\n");
      out.write("\r\n");
      out.write("				</H3>\r\n");
      out.write("\r\n");
      out.write("				<H3 align=\"center\">\r\n");
      out.write("\r\n");
      out.write("					<font color=\"green\"> ");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</font>\r\n");
      out.write("\r\n");
      out.write("				</H3>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"id\" value=\"");
      out.print(bean.getId());
      out.write("\"> <input\r\n");
      out.write("				type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(bean.getCreatedBy());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"modifiedBy\"\r\n");
      out.write("				value=\"");
      out.print(bean.getModifiedBy());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"createdDatetime\"\r\n");
      out.write("				value=\"");
      out.print(DataUtility.getTimestamp(bean.getCreatedDatetime()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"modifiedDatetime\"\r\n");
      out.write("				value=\"");
      out.print(DataUtility.getTimestamp(bean.getModifiedDatetime()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("\r\n");
      out.write("					<th align=\"left\">Vehicle Name <span style=\"color: red\">*</span>\r\n");
      out.write("\r\n");
      out.write("					</th>\r\n");
      out.write("\r\n");
      out.write("					<td><input type=\"text\" name=\"vehicleName\"\r\n");
      out.write("						placeholder=\"Enter Vehicle Name\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getVehicleName()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("\r\n");
      out.write("					<td style=\"position: fixed\"><font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("vehicleName", request));
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</font></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("\r\n");
      out.write("					<th align=\"left\">Model <span style=\"color: red\">*</span>\r\n");
      out.write("\r\n");
      out.write("					</th>\r\n");
      out.write("\r\n");
      out.write("					<td><input type=\"text\" name=\"model\" placeholder=\"Enter Model\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getModel()));
      out.write("\"></td>\r\n");
      out.write("\r\n");
      out.write("					<td style=\"position: fixed\"><font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("model", request));
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</font></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("\r\n");
      out.write("					<th align=\"left\">Company <span style=\"color: red\">*</span>\r\n");
      out.write("\r\n");
      out.write("					</th>\r\n");
      out.write("\r\n");
      out.write("					<td><input type=\"text\" name=\"company\"\r\n");
      out.write("						placeholder=\"Enter Company\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getCompany()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("\r\n");
      out.write("					<td style=\"position: fixed\"><font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("company", request));
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</font></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("\r\n");
      out.write("					<th align=\"left\">Price <span style=\"color: red\">*</span>\r\n");
      out.write("\r\n");
      out.write("					</th>\r\n");
      out.write("\r\n");
      out.write("					<td><input type=\"text\" name=\"price\" placeholder=\"Enter Price\"\r\n");
      out.write("						value=\"");
      out.print((bean.getPrice() == 0) ? "" : bean.getPrice());
      out.write("\"></td>\r\n");
      out.write("\r\n");
      out.write("					<td style=\"position: fixed\"><font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("price", request));
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</font></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("\r\n");
      out.write("					<th></th>\r\n");
      out.write("\r\n");
      out.write("					");

					if (bean != null && bean.getId() > 0) {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<td align=\"left\" colspan=\"2\"><input type=\"submit\"\r\n");
      out.write("						name=\"operation\" value=\"");
      out.print(VehicleCtl.OP_UPDATE);
      out.write("\"> <input\r\n");
      out.write("						type=\"submit\" name=\"operation\" value=\"");
      out.print(VehicleCtl.OP_CANCEL);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("\r\n");
      out.write("					");

					} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<td align=\"left\" colspan=\"2\"><input type=\"submit\"\r\n");
      out.write("						name=\"operation\" value=\"");
      out.print(VehicleCtl.OP_SAVE);
      out.write("\"> <input\r\n");
      out.write("						type=\"submit\" name=\"operation\" value=\"");
      out.print(VehicleCtl.OP_RESET);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
